services:
  db:
    image: postgres:15
    container_name: hfg_postgres
    restart: always
    environment:
      POSTGRES_DB: hfg_db
      POSTGRES_USER: hfg_user
      POSTGRES_PASSWORD: hfg_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: